Index.Aduana.UI/Controllers/Materia_PrimaController.cs
using Index.Aduana.BLL;
using Index.Aduana.Entities;
using Index.Aduana.UI.App_Start;
using Index.Aduana.UI.Models;
using Sistema.Seguridad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;

namespace Index.Aduana.UI.Controllers
{
    [Authorize]
    [HandleError]
    public class Materia_PrimaController : Controller
    {
        #region Metodos Privados

            private void CargaControles()
            {
                var Unidades = new UnidadBL().ObtenerListado();
                var Cuentas = new CuentaBL().ObtenerCuentaPorClienteId(CustomHelper.getClienteId());

                ViewBag.Unidades = new SelectList(Unidades, "UnidadId", "Nombre");
                ViewBag.Cuentas = new SelectList(Cuentas, "CuentaId", "Nombre");   
            }

        #endregion

        // GET: Materia_Prima
        [Permiso("Index.Materia_Prima.Ver_Listado")]
        public ActionResult Index(int? page, string search)
        {
            CustomHelper.setTitle("Materia Prima", "Listado");

            List<Materia> Materias = new List<Materia>();

            try
            {
                if (!string.IsNullOrWhiteSpace(search) && search != null)
                {
                    Materias = new MateriaBL().Buscar(search,CustomHelper.getClienteId()).ToList();
                }
                else
                {
                    Materias = new MateriaBL().ObtenerListado(CustomHelper.getClienteId()).ToList();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = string.Format("Message: {0} StackTrace: {1}", ex.Message, ex.StackTrace);
                return View("~/Views/Shared/Error.cshtml");
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(Materias.ToPagedList(pageNumber, pageSize));
        }

        [Permiso("Index.Materia_Prima.Crear")]
        public ActionResult Crear()
        {
            CustomHelper.setTitle("Materia Prima", "Nuevo");         

            this.CargaControles();
            return View();
        }

        [Permiso("Index.Materia_Prima.Crear")]
        [HttpPost]
        public ActionResult Crear(Materia modelo)
        {          
            if (ModelState.IsValid)
            {
                modelo.ClienteId = CustomHelper.getClienteId();
                string strMensaje = new MateriaBL().Guardar(modelo);

                if (strMensaje.Equals("OK"))
                {
                    TempData["Materia_Prima-Success"] = strMensaje;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", strMensaje);
                }
            }
           
            this.CargaControles();
            return View(modelo);
        }

        [Permiso("Index.Materia_Prima.Editar")]
        public ActionResult Editar(long id)
        {
            Materia MateriaActual = new MateriaBL().ObtenerPorId(id);

            if (MateriaActual == null)
            {
                return HttpNotFound();
            }

            CustomHelper.setTitle("Materia Prima", "Editar");          

            this.CargaControles();
            return View(MateriaActual);
        }

        [Permiso("Index.Materia_Prima.Editar")]
        [HttpPost]
        public ActionResult Editar(Materia modelo)
        {
            if (ModelState.IsValid)
            {
                modelo.ClienteId = CustomHelper.getClienteId();
                string strMensaje = new MateriaBL().Guardar(modelo);

                if (strMensaje.Equals("OK"))
                {
                    TempData["Materia_Prima-Success"] = strMensaje;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", strMensaje);
                }
            }          

            this.CargaControles();
            return View(modelo);
        }        
    }
}

Index.Aduana.UI/Views/Materia_Prima/Crear.cshtml
@model Index.Aduana.Entities.Materia

@{
    ViewBag.Title = "Nueva Materia Prima";
}

<div class="row">
    <div class="col-md-12">
        <!-- start: FORM VALIDATION 1 PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="icon-external-link-sign"></i>
                Nueva Materia Prima
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="javascript:void(0)">
                    </a>
                    <a class="btn btn-xs btn-link panel-expand" href="javascript:void(0)">
                        <i class="icon-resize-full"></i>
                    </a>
                    <a class="btn btn-xs btn-link panel-close" href="javascript:void(0)">
                        <i class="icon-remove"></i>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <h2><i class="icon-edit-sign teal"></i> Nueva Materia Prima</h2>
                <p>
                    Crea una nueva materia prima.
                </p>
                <hr>
                <form action="" role="form" id="formaprincipal" name="formaprincipal" method="post">
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="col-md-12">
                            @if (ViewData.ModelState.Values.Any(x => x.Errors.Count > 0))
                            {
                                <div class="alert alert-danger">
                                    <button class="close" data-dismiss="alert">×</button>
                                    <h4 class="alert-heading">Error</h4>
                                    @Html.ValidationSummary(false)
                                </div>
                            }
                        </div>                        
                    </div>
                    @Html.Partial("_CreateOrEdit")                    
                    <div class="row">
                        <p>
                            <div class="col-md-6">
                                <button data-style="slide-down" class="btn btn-med-grey btn-block ladda-button" type="submit" tabindex="13">
                                    <span class="ladda-label"> Aceptar </span>
                                    <span class="ladda-spinner"></span>
                                    <span class="ladda-progress" style="width: 0px;"></span>
                                </button>
                            </div>
                        </p>
                        <p>
                            <div class="col-md-6">
                                <a class="btn btn-med-grey btn-block" href="@Url.Action("Index", "Materia_Prima")" tabindex="14">
                                    Regresar <i class="icon-prev"></i>
                                </a>
                            </div>
                        </p>
                    </div>
                </form>
            </div>
        </div>
        <!-- end: FORM VALIDATION 1 PANEL -->
    </div>
</div>

Index.Aduana.UI/Views/Materia_Prima/Editar.cshtml
@model Index.Aduana.Entities.Materia

@{
    ViewBag.Title = "Editar Materia Prima";
}

<div class="row">
    <div class="col-md-12">
        <!-- start: FORM VALIDATION 1 PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="icon-external-link-sign"></i>
                Editar Materia Prima
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="javascript:void(0)">
                    </a>
                    <a class="btn btn-xs btn-link panel-expand" href="javascript:void(0)">
                        <i class="icon-resize-full"></i>
                    </a>
                    <a class="btn btn-xs btn-link panel-close" href="javascript:void(0)">
                        <i class="icon-remove"></i>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <h2><i class="icon-edit-sign teal"></i> Editar Materia Prima</h2>
                <p>
                    Editar una materia prima.
                </p>
                <hr>
                <form action="" role="form" id="formaprincipal" name="formaprincipal" method="post">
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="col-md-12">
                            @if (ViewData.ModelState.Values.Any(x => x.Errors.Count > 0))
                            {
                                <div class="alert alert-danger">
                                    <button class="close" data-dismiss="alert">×</button>
                                    <h4 class="alert-heading">Error</h4>
                                    @Html.ValidationSummary(false)
                                </div>
                            }
                        </div>
                        <input type="hidden" id="MateriaId" name="MateriaId" value="@Html.Raw(Model.MateriaId)" />
                    </div>
                    @Html.Partial("_CreateOrEdit")
                    <div class="row">
                        <p>
                            <div class="col-md-6">
                                <button data-style="slide-down" class="btn btn-med-grey btn-block ladda-button" type="submit" tabindex="13">
                                    <span class="ladda-label"> Aceptar </span>
                                    <span class="ladda-spinner"></span>
                                    <span class="ladda-progress" style="width: 0px;"></span>
                                </button>
                            </div>
                        </p>
                        <p>
                            <div class="col-md-6">
                                <a class="btn btn-med-grey btn-block" href="@Url.Action("Index", "Materia_Prima")" tabindex="14">
                                    Regresar <i class="icon-prev"></i>
                                </a>
                            </div>
                        </p>
                    </div>
                </form>
            </div>
        </div>
        <!-- end: FORM VALIDATION 1 PANEL -->
    </div>
</div>

Index.Aduana.UI/Views/Materia_Prima/Index.cshtml
@model PagedList.IPagedList<Index.Aduana.Entities.Materia>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Materia Prima Listado";
}

<div>
    <a class="btn btn-light-grey" href="@Url.Action("Crear", "Materia_Prima")">
        Nueva
        <i class="icon-circle-arrow-right"></i>
    </a>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <form action="" method="get" class="form-inline">
            <div class="input-group well">
                <input type="text" class="form-control" id="search" name="search" placeholder="Buscar.." value="@Html.Raw(ViewBag.Search)" autocomplete="off" style="margin-bottom: 1px;">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="button">
                        <i class="clip-search-3"></i> Buscar
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- start: BASIC TABLE PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="icon-external-link-sign"></i>
                Materia Prima
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="javascript:void(0)">
                    </a>
                    <a class="btn btn-xs btn-link panel-expand" href="javascript:void(0)">
                        <i class="icon-resize-full"></i>
                    </a>
                    <a class="btn btn-xs btn-link panel-close" href="javascript:void(0)">
                        <i class="icon-remove"></i>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-hover" id="sample-table-1">
                    <thead>
                        <tr>
                            <th>C&oacute;digo</th>
                            <th>Nombre</th>
                            <th>Barra</th>
                            <th>Partida</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Materia in Model)
                        {
                            <tr>
                                <td>@Materia.Codigo</td>
                                <td>@Materia.Nombre</td>
                                <td>@Materia.Barra</td>
                                <td>@Materia.Partida</td>                                
                                <td class="center">
                                    <div class="visible-md visible-lg hidden-sm hidden-xs">
                                        <a href="@Url.Action("Editar", "Materia_Prima", new { id = Materia.MateriaId })" class="btn btn-teal tooltips" data-placement="top" data-original-title="Editar"><i class="icon-edit"></i></a>                                     
                                    </div>
                                    <div class="visible-xs visible-sm hidden-md hidden-lg">
                                        <div class="btn-group">
                                            <a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
                                                <i class="icon-cog"></i> <span class="caret"></span>
                                            </a>
                                            <ul role="menu" class="dropdown-menu pull-right">
                                                <li role="presentation">
                                                    <a role="menuitem" tabindex="-1" href="@Url.Action("Editar", "Materia_Prima", new { id = Materia.MateriaId })">
                                                        <i class="icon-edit"></i> Editar
                                                    </a>
                                                </li>                                            
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end: BASIC TABLE PANEL -->
    </div>
</div>

Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { search = ViewBag.Search, page }))

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function ()
        {
            if ('@TempData["Materia_Prima-Success"]' == "OK")
            {
                toastr.success('La materia prima se guardó exitosamente');
            }
        });
    </script>
}

Index.Aduana.UI/Views/Materia_Prima/_CreateOrEdit.cshtml
@model Index.Aduana.Entities.Materia

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">
                Codigo<span class="symbol required"></span>
            </label>
            @Html.TextBoxFor(model => model.Codigo, new { @class = "form-control", @placeholder = "Código de la Materia Prima", required = "required", autocomplete = "off", autofocus = "autofocus", @tabindex = 1 })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">       
        <div class="form-group">
            <label class="control-label">
                Nombre<span class="symbol required"></span>
            </label>
            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre de la Materia Prima", required = "required", autocomplete = "off", @tabindex = 2 })
        </div>
        <div class="form-group">
            <label class="control-label">
                Descripci&oacute;n<span class="symbol required"></span>
            </label>
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Descripción de la Materia Prima", required = "required", autocomplete = "off", @tabindex = 3 })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">
                Barra<span class="symbol required"></span>
            </label>
            @Html.TextBoxFor(model => model.Barra, new { @class = "form-control", @placeholder = "Barra de la Materia Prima", required = "required", autocomplete = "off", @tabindex = 4 })
        </div>        
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">
                Partida<span class="symbol required"></span>
            </label>
            @Html.TextBoxFor(model => model.Partida, new { @class = "form-control", @placeholder = "Partida de la Materia Prima", required = "required", autocomplete = "off", @tabindex = 5 })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><i class="icon-edit-sign teal"></i>Unidades de Medida</h2>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">
                Unidad<span class="symbol required"></span>
            </label>
            @Html.DropDownList("UnidadId", (SelectList)ViewBag.Unidades, "--Seleccione una Unidad--", new { @class = "form-control search-select required", @tabindex = 6 })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><i class="icon-edit-sign teal"></i>Cuentas</h2>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">
                Cuenta<span class="symbol required"></span>
            </label>
            @Html.DropDownList("CuentaId", (SelectList)ViewBag.Cuentas, "--Seleccione una Cuenta--", new { @class = "form-control search-select required", @tabindex = 7 })
        </div>
    </div>
</div>